export interface CreateVdHead {
  flag: number;
  formId: string
  accNoVendor: string
  akont: string
  approveStatus: string
  blockStatus: string
  city1: string
  city2: string
  compCode: string
  confirmStatus: string
  country: string
  currencyKey: string
  faxExtens: string
  faxNumber: string
  fdgrv: string
  flagDoubleInvo: string
  houseNum1: string
  indWithholdingTax: string
  indWithholdingTax2: string
  indWithholdingTax3: string
  langKey: string
  location: string
  name1: string
  name2: string
  name3: string
  postCode1: string
  purchasOrg: string
  searchTerm: string
  stcd1: string
  strSuppl1: string
  strSuppl3: string
  street: string
  telExtens: string
  telNumber: string
  tndGrInv: string
  typeRecipient: string
  typeRecipient2: string
  typeRecipient3: string
  userWeb: string
  vendorAccGroup: string
  wtTaxCode: string
  wtTaxCode2: string
  wtTaxCode3: string
  wtTaxType: string
  wtTaxType2: string
  wtTaxType3: string
  zterm1: string
  zterm2: string
  zzpmt: string
}